In [6]:
import json, sys, os
import tensorflow as tf
from tensorflow.keras.layers import *
import numpy as np
import sklearn 

In [63]:
display(tf.__version__)

'2.8.0'

In [8]:
foo = '[ "12:01:32.686 PM 04-Mar-2024" , "BET" , {"name":"danny", "bet":1.0, "folded":"false", "round_winner_by_cards": "charlie", "chips":14.0, "face_down_cards":[["2","diamond"]], "face_up_cards":[["2","heart"],["9","diamond"],["8","diamond"]],"face_player_cards":[["3","heart"]],"all_cards":[["2","diamond"],["3","heart"],["8","diamond"],["2","heart"],["9","diamond"]], "handvalue":"one pair"}]'
foo

'[ "12:01:32.686 PM 04-Mar-2024" , "BET" , {"name":"danny", "bet":1.0, "folded":"false", "round_winner_by_cards": "charlie", "chips":14.0, "face_down_cards":[["2","diamond"]], "face_up_cards":[["2","heart"],["9","diamond"],["8","diamond"]],"face_player_cards":[["3","heart"]],"all_cards":[["2","diamond"],["3","heart"],["8","diamond"],["2","heart"],["9","diamond"]], "handvalue":"one pair"}]'

In [10]:
my_row = json.loads(foo)
my_row

['12:01:32.686 PM 04-Mar-2024',
 'BET',
 {'name': 'danny',
  'bet': 1.0,
  'folded': 'false',
  'round_winner_by_cards': 'charlie',
  'chips': 14.0,
  'face_down_cards': [['2', 'diamond']],
  'face_up_cards': [['2', 'heart'], ['9', 'diamond'], ['8', 'diamond']],
  'face_player_cards': [['3', 'heart']],
  'all_cards': [['2', 'diamond'],
   ['3', 'heart'],
   ['8', 'diamond'],
   ['2', 'heart'],
   ['9', 'diamond']],
  'handvalue': 'one pair'}]

In [11]:
my_row[0]

'12:01:32.686 PM 04-Mar-2024'

In [12]:
my_row[1]

'BET'

In [16]:
my_row[2]

{'name': 'danny',
 'bet': 1.0,
 'folded': 'false',
 'round_winner_by_cards': 'charlie',
 'chips': 14.0,
 'face_down_cards': [['2', 'diamond']],
 'face_up_cards': [['2', 'heart'], ['9', 'diamond'], ['8', 'diamond']],
 'face_player_cards': [['3', 'heart']],
 'all_cards': [['2', 'diamond'],
  ['3', 'heart'],
  ['8', 'diamond'],
  ['2', 'heart'],
  ['9', 'diamond']],
 'handvalue': 'one pair'}

In [17]:
my_row[2]["round_winner_by_cards"]

'charlie'

In [5]:
infilename = "./poker.jsonl"
data = []
infile = open(infilename,"r")
for row in infile:
    data.append(json.loads(row))
display(data[100])

['12:01:30.659 PM 04-Mar-2024',
 'BET',
 {'name': 'elissa',
  'bet': 0.0,
  'folded': True,
  'round_winner_by_cards': 'bob',
  'chips': 0.0,
  'face_down_cards': [],
  'face_up_cards': [['4', 'diamond']],
  'face_player_cards': [['2', 'heart'],
   ['queen', 'club'],
   ['9', 'club'],
   ['4', 'spade']],
  'all_cards': [['2', 'heart'],
   ['9', 'club'],
   ['4', 'diamond'],
   ['4', 'spade'],
   ['queen', 'club']],
  'handvalue': 'one pair'},
 {'name': 'bob',
  'bet': 0.0,
  'folded': False,
  'round_winner_by_cards': 'bob',
  'chips': 23.0,
  'face_down_cards': [['6', 'heart'], ['6', 'diamond']],
  'face_up_cards': [['jack', 'spade'], ['5', 'heart']],
  'face_player_cards': [['9', 'spade']],
  'all_cards': [['9', 'spade'],
   ['5', 'heart'],
   ['6', 'diamond'],
   ['jack', 'spade'],
   ['6', 'heart']],
  'handvalue': 'one pair'},
 {'name': 'danny',
  'bet': 2.0,
  'folded': False,
  'round_winner_by_cards': 'bob',
  'chips': 21.0,
  'face_down_cards': [['4', 'heart'], ['9', 'heart']]

In [75]:
model = tf.keras.Sequential()
model.add(tf.keras.Input(52))
model.add(tf.keras.layers.Dense(100,activation="relu"))
model.add(tf.keras.layers.Dense(1))
model.build()#(None, 16))
print(model.summary())

Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_15 (Dense)            (None, 100)               5300      
                                                                 
 dense_16 (Dense)            (None, 1)                 101       
                                                                 
Total params: 5,401
Trainable params: 5,401
Non-trainable params: 0
_________________________________________________________________
None


In [76]:
model(tf.ones((1,10)))

ValueError: Input 0 of layer "sequential_6" is incompatible with the layer: expected shape=(None, 52), found shape=(1, 10)

In [77]:
tf.ones((1,10)).numpy()

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]], dtype=float32)

In [78]:
cards_rows = list(sorted(map(lambda x : x[2].get("all_cards",[]) , data[1000:2100])))
foo = set()
for cardrow in cards_rows:
    # print(cardrow)
    for card in cardrow:
        foo.update([str(card)])
all_cards = list(map(eval,foo))

In [79]:
display(len(all_cards))
# cd = {}
# counter = 0
# for card in 

52

In [93]:
x = list(map(lambda x: 1.0 if x == ['king', 'diamond'] else 0.0, all_cards))
model(np.array([x],dtype="float32").reshape((1,52)))

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[-0.07683166]], dtype=float32)>

In [95]:
np.array(x)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0.])

In [91]:
model(tf.ones((1,52)))

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[-0.07177815]], dtype=float32)>

In [96]:
def player_card(row):
    field = "face_player_cards"
    if field not in row[2]:
        return "."
    card = row[2][field][0]
    return list(map(lambda x: 1 if x == card else 0, all_cards))
x = list(map(player_card,data[10:20]))


In [103]:
model(np.array(x).reshape((-1,52)))

<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[-0.07683167],
       [-0.06291442],
       [ 0.13455272],
       [-0.06291442],
       [ 0.13455272],
       [ 0.13455272],
       [ 0.13455272],
       [-0.07683167],
       [-0.07683167],
       [-0.06291442]], dtype=float32)>

In [102]:
np.array(x).reshape((-1,52))

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0